// GENERATED by scripts/warm-palette.mjs — do not edit by hand.
//
// Tailwind's stock families, shifted to 3800K so the reds, blues and greens
// the components borrow sit in the same night light as the palette proper.
// The trailing comment on each line is the neutral (D65) value it came from.
export const nightPalette = {
  paper: "#ffcf9c", // #ffffff
  red: {
    50: "#fec494", // #fef2f2
    100: "#feb78a", // #fee2e2
    200: "#fea47c", // #fecaca
    300: "#fc8665", // #fca5a5
    400: "#f85c45", // #f87171
    500: "#ef372a", // #ef4444
    600: "#dc1f17", // #dc2626
    700: "#b91711", // #b91c1c
    800: "#991611", // #991b1b
    900: "#7f1812", // #7f1d1d
    950: "#450806", // #450a0a
  },
  yellow: {
    50: "#fecd8e", // #fefce8
    100: "#feca77", // #fef9c3
    200: "#fec354", // #fef08a
    300: "#fdb62b", // #fde047
    400: "#faa60d", // #facc15
    500: "#ea9105", // #eab308
    600: "#ca7002", // #ca8a04
    700: "#a15004", // #a16207
    800: "#853e09", // #854d0e
    900: "#71330b", // #713f12
    950: "#421a04", // #422006
  },
  blue: {
    50: "#efc89c", // #eff6ff
    100: "#dbbe9b", // #dbeafe
    200: "#bfb29b", // #bfdbfe
    300: "#93a09b", // #93c5fd
    400: "#608699", // #60a5fa
    500: "#3b6a96", // #3b82f6
    600: "#255090", // #2563eb
    700: "#1d3f84", // #1d4ed8
    800: "#1e346b", // #1e40af
    900: "#1e2f54", // #1e3a8a
    950: "#171e33", // #172554
  },
  emerald: {
    50: "#eccd96", // #ecfdf5
    100: "#d1cb8c", // #d1fae5
    200: "#a7c57f", // #a7f3d0
    300: "#6ebb70", // #6ee7b7
    400: "#34ab5e", // #34d399
    500: "#10964f", // #10b981
    600: "#057a40", // #059669
    700: "#046135", // #047857
    800: "#064d2b", // #065f46
    900: "#063f24", // #064e3b
    950: "#022415", // #022c22
  },
  pink: {
    50: "#fdc498", // #fdf2f8
    100: "#fcbb95", // #fce7f3
    200: "#fba88e", // #fbcfe8
    300: "#f98882", // #f9a8d4
    400: "#f45d6f", // #f472b6
    500: "#ec3a5e", // #ec4899
    600: "#db2049", // #db2777
    700: "#be1339", // #be185d
    800: "#9d132f", // #9d174d
    900: "#831329", // #831843
    950: "#500616", // #500724
  },
  stone: {
    50: "#facb98", // #fafaf9
    100: "#f5c795", // #f5f5f4
    200: "#e7ba8b", // #e7e5e4
    300: "#d6ab80", // #d6d3d1
    400: "#a88361", // #a8a29e
    500: "#785c42", // #78716c
    600: "#574330", // #57534e
    700: "#443425", // #44403c
    800: "#291e16", // #292524
    900: "#1c140e", // #1c1917
    950: "#0c0806", // #0c0a09
  },
};
